import {
  ArrowLeft,
  ArrowRight,
  Bookmark,
  Check,
  ChevronDown,
  CircleUser,
  Eye,
  EyeOff,
  Heart,
  Loader,
  Menu,
  Minus,
  PencilLine,
  Plus,
  Share2,
  ShoppingBag,
  ShoppingCart,
  SlidersHorizontal,
  Trash2,
  X,
} from "lucide-react";

export const Icons = {
  down: ChevronDown,
  right: ArrowRight,
  cart: ShoppingCart,
  heart: Heart,
  menu: Menu,
  bookmark: Bookmark,
  share: Share2,
  plus: Plus,
  minus: Minus,
  left: ArrowLeft,
  delete: Trash2,
  close: X,
  filter: SlidersHorizontal,
  check: Check,
  pen: PencilLine,
  eyeOpen: Eye,
  eyeClose: EyeOff,
  bag: ShoppingBag,
  person: CircleUser,
  loader: Loader,
};
