import {
  ChevronDown,
  ArrowRight,
  ShoppingCart,
  Heart,
  Menu,
  Bookmark,
  Share2,
  Plus,
  Minus,
  ArrowLeft,
  Trash2,
  X,
  SlidersHorizontal,
  Check,
  PencilLine,
  Eye,
  EyeOff,
  ShoppingBag,
  CircleUser,
} from 'lucide-react';

export const Icons = {
  down: ChevronDown,
  right: ArrowRight,
  cart: ShoppingCart,
  heart: Heart,
  menu: Menu,
  bookmark: Bookmark,
  share: Share2,
  plus: Plus,
  minus: Minus,
  left: ArrowLeft,
  delete: Trash2,
  close: X,
  filter: SlidersHorizontal,
  check: Check,
  pen: PencilLine,
  eyeOpen: Eye,
  eyeClose: EyeOff,
  bag: ShoppingBag,
  person: CircleUser,
};
