import type { Metadata } from 'next';
import { inter, roboto, firaCode } from './fonts';
import './globals.css';
import MainNav from '@/components/navigation/main-nav';
import Footer from '@/components/footer/footer';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body
        className={`${inter.variable} ${roboto.variable} ${firaCode.variable} font-roboto bg-background overflow-x-clip`}
      >
        <MainNav />
        {children}
        <Footer />
      </body>
    </html>
  );
}
